CREATE TABLE games (
	gameId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	player1UUID TEXT NOT NULL,
	player2UUID TEXT NOT NULL,
	"start" TEXT,
	"end" TEXT,
	tournamentId INTEGER,
	CONSTRAINT games_FK FOREIGN KEY (player2UUID) REFERENCES players(playerUUID) ON UPDATE CASCADE,
	CONSTRAINT games_FK_1 FOREIGN KEY (player1UUID) REFERENCES players(playerUUID) ON UPDATE CASCADE,
	CONSTRAINT games_FK_2 FOREIGN KEY (tournamentId) REFERENCES tournaments(tournamentId) ON UPDATE CASCADE
);

CREATE TABLE players (
	playerUUID TEXT(128) NOT NULL,
	email TEXT(256) NOT NULL,
	pseudo TEXT(100) NOT NULL,
	timeToKill INTEGER,
	numberOfWin INTEGER NOT NULL,
	numberOfLoose INTEGER NOT NULL, password TEXT NOT NULL,
	CONSTRAINT players_PK PRIMARY KEY (playerUUID)
);
CREATE TABLE tournaments (
	tournamentId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT(128) NOT NULL
);