CREATE TABLE games (
	gameId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	player1UUID TEXT NOT NULL,
	player2UUID TEXT NOT NULL,
	"start" TEXT,
	"end" TEXT,
	tournamentId INTEGER,
	CONSTRAINT games_FK FOREIGN KEY (player2UUID) REFERENCES players(playerUUID) ON UPDATE CASCADE,
	CONSTRAINT games_FK_1 FOREIGN KEY (player1UUID) REFERENCES players(playerUUID) ON UPDATE CASCADE,
	CONSTRAINT games_FK_2 FOREIGN KEY (tournamentId) REFERENCES tournaments(tournamentId) ON UPDATE CASCADE
);

CREATE TABLE players (
	playerUUID TEXT(128) NOT NULL UNIQUE,
	email TEXT(256) NOT NULL UNIQUE,
	pseudo TEXT(100) NOT NULL UNIQUE,
	timeToKill FLOAT NOT NULL DEFAULT 0,
	numberOfWin INTEGER NOT NULL DEFAULT 0,
	numberOfLoose INTEGER NOT NULL DEFAULT 0, 
	password TEXT NOT NULL,
	numberOfSoloGamePlay INTEGER NOT NULL DEFAULT 0,
	CONSTRAINT players_PK PRIMARY KEY (playerUUID)
);
CREATE TABLE tournaments (
	tournamentId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT(128) NOT NULL
);